#!/usr/bin/env python3
"""Export the decision log as markdown.

The SQLite queue is local run state and is gitignored, but the audit trail --
what was proposed, who decided what, and what was written -- belongs in the repo.

    python ops/export_runlog.py > RUNLOG.md
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from bellhaven import store  # noqa: E402

ICON = {"applied": "applied", "rejected": "rejected", "obsolete": "auto-retired",
        "pending": "pending", "approved": "approved", "failed": "FAILED"}


def main() -> None:
    st = store.Store()
    rows = st.list_proposals()
    counts = st.counts()
    print("# Run log\n")
    print("Generated by `python ops/export_runlog.py`. One row per proposal the "
          "pipeline raised, with the decision a reviewer made and the writes that "
          "resulted.\n")
    print("| status | " + " | ".join(f"{k}: {v}" for k, v in sorted(counts.items())) + " |")
    print("|---|" + "---|" * len(counts) + "\n")

    for kind in sorted({r["kind"] for r in rows}):
        print(f"\n## {kind}\n")
        for r in [x for x in rows if x["kind"] == kind]:
            print(f"### {r['title']}")
            print(f"`{r['fingerprint']}` &middot; **{ICON.get(r['status'], r['status'])}**"
                  f" &middot; {r['severity']}"
                  + (f" &middot; decided by {r['decided_by']}" if r["decided_by"] else ""))
            print(f"\n{r['rationale']}\n")
            if r["decision_note"]:
                print(f"> Reviewer: {r['decision_note']}\n")
            print("Writes:\n")
            print("```json")
            print(json.dumps(json.loads(r["actions_json"]), indent=2))
            print("```\n")
            print("Evidence:\n")
            for e in json.loads(r["evidence_json"]):
                print(f"- {e}")
            print()


if __name__ == "__main__":
    main()
